@baseUrl = http://localhost:3001/api

@userId = 7
@postId = 20


@tokenJWT = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4NDY0NDc4OSwiZXhwIjoxNzg0NzMxMTg5fQ.M3aS7wBSvi2Wb-0Kz8qaVTBGC7xPBsOeAWTZAzQ__p8

### =========================================
### POSTS - Criar post (aninhado no usuário)
### =========================================
POST {{baseUrl}}/user/posts
Content-Type: application/json
Authorization:  {{tokenJWT}}


{
  "title": "E nesse dia eu aprendi que a vida é feita de escolhas",
  "content": "As escolhas do homem são o que definem o seu caráter. E a vida é feita de escolhas, e cada escolha que fazemos nos leva a um caminho diferente. E é nesse caminho que encontramos a nossa verdadeira essência.",
  "category": "imaginação",
  "tags": ["sonho"]
}

### =========================================
### GET - Listar todos
### =========================================
GET {{baseUrl}}/user/posts
Authorization:  {{tokenJWT}}


### =========================================
### DELETE - Deletar
### =========================================
DELETE {{baseUrl}}/user/posts/{{postId}}
Authorization:  {{tokenJWT}}



### =========================================
### PATCH - Atualizar (PUT - substitui o recurso inteiro)
### =========================================
PATCH {{baseUrl}}/user/posts/{{postId}}
Content-Type: application/json
Authorization:  {{tokenJWT}}

{
  "title": "Harry Potter 3 (editado)",
  "category": "imaginação",
  "tags": ["imaginacao", "magia"],
  "published": true
}

### =========================================
### GET - Buscar por id do post (aninhado no usuário)
### =========================================
GET {{baseUrl}}/user/posts/{{postId}}
Authorization:  {{tokenJWT}}


