@baseUrl = http://localhost:3001/api
@term = .com

### Criar usuário
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "email": "brutos.jj@apple.com",
  "name": "Vitor Brutos",
  "password": "123456"
}

### Listar usuários
GET {{baseUrl}}/users


### Buscar usuários por trecho de email
GET {{baseUrl}}/users/search-email
  ?email={{term}}
